<a href="https://colab.research.google.com/github/hbetabessi/ultra-marathon-eda/blob/main/ultra_marathon_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd

In [83]:
import seaborn as sns

In [84]:
df =pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

/tmp/ipython-input-2504010129.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df =pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

In [85]:
# see the data that's being imported

In [86]:
df.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22.0,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0.0
1,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1.0
2,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2.0
3,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3.0
4,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4.0
5,2018,06.01.2018,Selva Costera (CHI),50km,22.0,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5.0
6,2018,06.01.2018,Selva Costera (CHI),50km,22.0,6:28:00 h,Los Patagones,ARG,1979.0,F,W35,7.732,6.0
7,2018,06.01.2018,Selva Costera (CHI),50km,22.0,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7.0
8,2018,06.01.2018,Selva Costera (CHI),50km,22.0,6:39:08 h,Puro Trail Osorno,CHI,1985.0,M,M23,7.516,8.0
9,2018,06.01.2018,Selva Costera (CHI),50km,22.0,6:45:11 h,Marlene Flores Team,CHI,1976.0,M,M40,7.404,9.0

In [87]:
df.shape

(3505553, 13)

In [88]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers    float64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                   float64
dtype: object

In [89]:
#clean up data

In [90]:
#only USA and 50k or 50M in 2020

In [91]:
df[df['Event distance/length'] == "50km"]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22.0,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0.0
1,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1.0
2,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2.0
3,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3.0
4,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3504895,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,7:29:36 h,"*Norwalk, CT",USA,1981.0,M,M40,6.673,919343.0
3505438,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,4:46:28 h,Nocando Marathon Club,FIN,1973.0,M,M45,10.472,618515.0
3505439,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,4:56:15 h,Pori Trail Runners,FIN,1983.0,F,W35,10.127,88177.0
3505440,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,5:19:59 h,TT Treenitehdas,FIN,1969.0,M,M50,9.375,1022702.0
3505441,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,5:19:59 h,APK-Maratoonarit,FIN,NaN,F,NaN,9.375,926478.0

In [92]:
df[df['Event distance/length'] == "50mi"]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3504646,2022,25.09.2022,Vermont 50 Miles Ultra Run (USA),50mi,115.0,12:11:12 h,NaN,USA,NaN,M,NaN,6.603,1022480.0
3504647,2022,25.09.2022,Vermont 50 Miles Ultra Run (USA),50mi,115.0,12:11:13 h,NaN,USA,NaN,M,NaN,6.603,1022481.0
3505435,2022,24.09.2022,Radioaseman Ultra Maraton 50 mailia (FIN),50mi,3.0,8:35:44 h,Honkajoen Seudun Urhei...,FIN,1979.0,M,M40,9.361,959322.0
3505436,2022,24.09.2022,Radioaseman Ultra Maraton 50 mailia (FIN),50mi,3.0,9:27:42 h,Ikaalinen,FIN,1968.0,M,M50,8.505,995628.0
3505437,2022,24.09.2022,Radioaseman Ultra Maraton 50 mailia (FIN),50mi,3.0,10:20:08 h,Team Nisulat,FIN,1991.0,M,M23,7.785,988151.0

In [93]:
df[df['Event distance/length'].isin(['50km', '50mi'])]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22.0,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0.0
1,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1.0
2,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2.0
3,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3.0
4,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505437,2022,24.09.2022,Radioaseman Ultra Maraton 50 mailia (FIN),50mi,3.0,10:20:08 h,Team Nisulat,FIN,1991.0,M,M23,7.785,988151.0
3505438,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,4:46:28 h,Nocando Marathon Club,FIN,1973.0,M,M45,10.472,618515.0
3505439,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,4:56:15 h,Pori Trail Runners,FIN,1983.0,F,W35,10.127,88177.0
3505440,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,5:19:59 h,TT Treenitehdas,FIN,1969.0,M,M50,9.375,1022702.0
3505441,2022,24.09.2022,Radioaseman Ultra Maraton 50 km (FIN),50km,4.0,5:19:59 h,APK-Maratoonarit,FIN,NaN,F,NaN,9.375,926478.0

In [94]:
df[(df['Event distance/length'].isin(['50km','50mi'])) & (df['Year of event'] ==2018)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22.0,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0.0
1,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1.0
2,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2.0
3,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3.0
4,2018,06.01.2018,Selva Costera (CHI),50km,22.0,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
661478,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29.0,17:05:58 h,NaN,USA,1972.0,M,M45,4.706,68122.0
661479,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29.0,18:13:01 h,NaN,USA,1953.0,M,M65,4.417,23336.0
661480,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29.0,18:49:58 h,NaN,USA,1986.0,M,M23,4.273,375022.0
661481,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29.0,23:30:00 h,NaN,USA,1952.0,M,M65,3.424,68273.0
661482,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29.0,25:40:10 h,NaN,USA,1951.0,M,M65,3.135,341648.0

In [95]:
df[df['Event name'] == 'Yankee Springs 50 Mile Winter Challenge (USA)']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3175861,2022,08.01.2022,Yankee Springs 50 Mile Winter Challenge (USA),50mi,15.0,11:39:57 h,"*Birmingham, MI",USA,1992.0,F,W23,6.898,271782.0
3175862,2022,08.01.2022,Yankee Springs 50 Mile Winter Challenge (USA),50mi,15.0,11:56:19 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.74,62.0
3175863,2022,08.01.2022,Yankee Springs 50 Mile Winter Challenge (USA),50mi,15.0,13:00:31 h,"*Byron center, MI",USA,1994.0,M,M23,6.186,815877.0
3175864,2022,08.01.2022,Yankee Springs 50 Mile Winter Challenge (USA),50mi,15.0,13:10:13 h,"*Brighton, MI",USA,1988.0,M,M23,6.11,845432.0
3175865,2022,08.01.2022,Yankee Springs 50 Mile Winter Challenge (USA),50mi,15.0,13:40:59 h,"*Barrington, IL",USA,1958.0,M,M60,5.881,56880.0

In [96]:
df[df['Event name'] == 'Yankee Springs 50 Mile Winter Challenge (USA)']['Event name'].str.split('(')

55         [Yankee Springs 50 Mile Winter Challenge , USA)]
56         [Yankee Springs 50 Mile Winter Challenge , USA)]
57         [Yankee Springs 50 Mile Winter Challenge , USA)]
58         [Yankee Springs 50 Mile Winter Challenge , USA)]
59         [Yankee Springs 50 Mile Winter Challenge , USA)]
                                 ...
3175861    [Yankee Springs 50 Mile Winter Challenge , USA)]
3175862    [Yankee Springs 50 Mile Winter Challenge , USA)]
3175863    [Yankee Springs 50 Mile Winter Challenge , USA)]
3175864    [Yankee Springs 50 Mile Winter Challenge , USA)]
3175865    [Yankee Springs 50 Mile Winter Challenge , USA)]
Name: Event name, Length: 96, dtype: object

In [97]:
df[df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3504891,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,6:47:29 h,"*Manalapan, NJ",USA,1995.0,M,M23,7.362,863326.0
3504892,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,6:48:41 h,"*Northampton, MA",USA,1978.0,M,M40,7.341,69515.0
3504893,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,7:00:47 h,"*Harrison, NJ",USA,1990.0,M,M23,7.13,766971.0
3504894,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,7:28:56 h,"*Spring Mills, PA",USA,1992.0,F,W23,6.683,322200.0
3504895,2022,25.09.2022,Angevine Farm 50 km Race (USA),50km,6.0,7:29:36 h,"*Norwalk, CT",USA,1981.0,M,M40,6.673,919343.0

In [98]:
df2 =df[(df['Event distance/length'].isin(['50km','50mi'])) & (df['Year of event'] ==2018) & (df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA')]

In [99]:
df2.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0
60,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,12:32:16 h,"*Olaton, KY",USA,1995.0,M,MU23,6.418,60.0
61,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,12:39:36 h,"*Wyoming, MI",USA,1979.0,M,M35,6.356,61.0
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62.0
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9.0,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63.0
64,2018,06.01.2018,Yankee Springs 50 km Winter Challenge (USA),50km,36.0,5:09:40 h,"*Okemos, MI",USA,1991.0,F,W23,9.688,64.0

In [100]:
df2.shape

(64299, 13)

In [101]:
#remove USA from event name

In [102]:
df2['Event name'].str.split('(').str.get(0)

55        Yankee Springs 50 Mile Winter Challenge
56        Yankee Springs 50 Mile Winter Challenge
57        Yankee Springs 50 Mile Winter Challenge
58        Yankee Springs 50 Mile Winter Challenge
59        Yankee Springs 50 Mile Winter Challenge
                            ...
661478                        Cactus Rose 50 Mile
661479                        Cactus Rose 50 Mile
661480                        Cactus Rose 50 Mile
661481                        Cactus Rose 50 Mile
661482                        Cactus Rose 50 Mile
Name: Event name, Length: 64299, dtype: object

In [103]:
df2['Event name'] = df2['Event name'].str.split('(').str.get(0)

/tmp/ipython-input-3473829760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Event name'] = df2['Event name'].str.split('(').str.get(0)

In [104]:
df2.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0
60,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,12:32:16 h,"*Olaton, KY",USA,1995.0,M,MU23,6.418,60.0
61,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,12:39:36 h,"*Wyoming, MI",USA,1979.0,M,M35,6.356,61.0
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62.0
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63.0
64,2018,06.01.2018,Yankee Springs 50 km Winter Challenge,50km,36.0,5:09:40 h,"*Okemos, MI",USA,1991.0,F,W23,9.688,64.0

In [105]:
#clean up the althete age

In [106]:
df2 ['Athlete_age'] = 2018 - df2['Athlete year of birth']

/tmp/ipython-input-3523140396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2 ['Athlete_age'] = 2018 - df2['Athlete year of birth']

In [107]:
#remove h from athlete performance

In [108]:
df2['Athlete performance'] = df2['Athlete performance'].str.split(' ').str.get(0)

/tmp/ipython-input-2477507555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Athlete performance'] = df2['Athlete performance'].str.split(' ').str.get(0)

In [109]:
df2.head(5)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID,Athlete_age
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,9:53:05,"*Middleville, MI",USA,1983.0,M,M23,8.141,55.0,35.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:09:35,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56.0,41.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:33:00,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57.0,42.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:38:17,"*Utica, MI",USA,1986.0,M,M23,6.914,58.0,32.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:56:35,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59.0,30.0

In [110]:
# drop columns: Athelte country, athlete age category, Athlete year of birth , Athlete  Club

In [111]:
df2 = df2.drop(['Athlete club', 'Athlete country' ,'Athlete year of birth' ,'Athlete age category'],axis=1)

In [112]:
df2.head(5)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,9:53:05,M,8.141,55.0,35.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:09:35,F,7.211,56.0,41.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:33:00,M,6.967,57.0,42.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:38:17,M,6.914,58.0,32.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:56:35,M,6.738,59.0,30.0

In [113]:
#clean up null values

In [114]:
df2.isna().sum()

Year of event                  0
Event dates                    0
Event name                     0
Event distance/length          0
Event number of finishers      0
Athlete performance            0
Athlete gender                 0
Athlete average speed          0
Athlete ID                     0
Athlete_age                  575
dtype: int64

In [115]:
df2[df2['Athlete_age'].isna()==1]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
453,2018,01.01.2018,Red Eye 50km,50km,21.0,5:10:00,M,9.677,453.0,NaN
456,2018,01.01.2018,Red Eye 50km,50km,21.0,5:44:00,M,8.721,456.0,NaN
459,2018,01.01.2018,Red Eye 50km,50km,21.0,6:07:00,M,8.174,459.0,NaN
460,2018,01.01.2018,Red Eye 50km,50km,21.0,6:12:00,M,8.065,460.0,NaN
13214,2018,17.03.2018,Lt. JC Stone 50K UltraMarathon,50km,34.0,4:54:43,F,10.179,12483.0,NaN
...,...,...,...,...,...,...,...,...,...,...
659684,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133.0,8:24:14,F,5.95,374269.0,NaN
659685,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133.0,8:25:12,F,5.938,358717.0,NaN
659688,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133.0,8:29:59,M,5.883,204804.0,NaN
659689,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133.0,8:31:30,F,5.865,374272.0,NaN
659690,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133.0,8:35:28,M,5.82,374273.0,NaN

In [116]:
df2 = df2.dropna()

In [119]:
df2.shape

(63724, 10)

In [ ]:
# check for duplicates

In [124]:
df2[df2.duplicated()==1]

Empty DataFrame
Columns: [Year of event, Event dates, Event name, Event distance/length, Event number of finishers, Athlete performance, Athlete gender, Athlete average speed, Athlete ID, Athlete_age]
Index: []

In [125]:
df2.reset_index(drop=True)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
0,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,9:53:05,M,8.141,55.0,35.0
1,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:09:35,F,7.211,56.0,41.0
2,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:33:00,M,6.967,57.0,42.0
3,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:38:17,M,6.914,58.0,32.0
4,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9.0,11:56:35,M,6.738,59.0,30.0
...,...,...,...,...,...,...,...,...,...,...
63719,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29.0,17:05:58,M,4.706,68122.0,46.0
63720,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29.0,18:13:01,M,4.417,23336.0,65.0
63721,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29.0,18:49:58,M,4.273,375022.0,32.0
63722,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29.0,23:30:00,M,3.424,68273.0,66.0
63723,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29.0,25:40:10,M,3.135,341648.0,67.0

In [ ]:
#fix types

In [126]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers    float64
Athlete performance           object
Athlete gender                object
Athlete average speed         object
Athlete ID                   float64
Athlete_age                  float64
dtype: object

In [127]:
df2['Athlete_age'] = df2['Athlete_age'].astype(int)

In [128]:
df2['Athlete average speed'] = df2['Athlete average speed'].astype(float)

In [129]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers    float64
Athlete performance           object
Athlete gender                object
Athlete average speed        float64
Athlete ID                   float64
Athlete_age                    int64
dtype: object

In [ ]:
#rename columns
#Year of event          Year_of_event
#Event dates	          Event_dates
#Event name	            Event_name
#Event distance/length	Event_distance/length
#Event number of finishers Event_number_of_finishers
#Athlete performance	  Athlete_performance
#Athlete gender	        Athlete_gender
#Athlete average speed	Athlete_average_speed
#Athlete ID	            Athlete_ID