<a href="https://colab.research.google.com/github/hbetabessi/ultra-marathon-eda/blob/main/ultra_marathon_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [183]:
import pandas as pd

In [184]:
import seaborn as sns

In [185]:
df =pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

/tmp/ipython-input-2504010129.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df =pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

In [186]:
# see the data that's being imported

In [187]:
df.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
5,2018,06.01.2018,Selva Costera (CHI),50km,22,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5
6,2018,06.01.2018,Selva Costera (CHI),50km,22,6:28:00 h,Los Patagones,ARG,1979.0,F,W35,7.732,6
7,2018,06.01.2018,Selva Costera (CHI),50km,22,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7
8,2018,06.01.2018,Selva Costera (CHI),50km,22,6:39:08 h,Puro Trail Osorno,CHI,1985.0,M,M23,7.516,8
9,2018,06.01.2018,Selva Costera (CHI),50km,22,6:45:11 h,Marlene Flores Team,CHI,1976.0,M,M40,7.404,9

In [188]:
df.shape

(1745198, 13)

In [189]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [190]:
#clean up data

In [191]:
#only USA and 50k or 50M in 2020

In [192]:
df[df['Event distance/length'] == "50km"]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745143,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,12:42:03 h,NaN,VEN,1978.0,M,M35,3.937,129256
1745144,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,12:59:48 h,NaN,VEN,1983.0,M,M23,3.847,634416
1745145,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:00:00 h,NaN,VEN,1968.0,M,M45,3.846,634417
1745146,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:05:36 h,NaN,VEN,1982.0,M,M23,3.819,248690
1745147,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:05:36 h,NaN,VEN,1968.0,M,M45,3.819,252211

In [193]:
df[df['Event distance/length'] == "50mi"]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740732,2017,09.12.2017,Deer Dodge 50 - 50 Miles (USA),50mi,20,13:18:53 h,"*Gainesville, FL",USA,1970.0,M,M45,6.043,309240
1740733,2017,09.12.2017,Deer Dodge 50 - 50 Miles (USA),50mi,20,13:32:40 h,"*Wiggins, MS",USA,1992.0,F,W23,5.941,549773
1740734,2017,09.12.2017,Deer Dodge 50 - 50 Miles (USA),50mi,20,13:37:28 h,"*Navarre, FL",USA,1977.0,F,W35,5.906,47377
1740735,2017,09.12.2017,Deer Dodge 50 - 50 Miles (USA),50mi,20,13:42:49 h,"*Milton, FL",USA,1980.0,F,W35,5.868,522832
1740736,2017,09.12.2017,Deer Dodge 50 - 50 Miles (USA),50mi,20,13:53:42 h,"*Dallas, GA",USA,1970.0,M,M45,5.791,633944

In [194]:
df[df['Event distance/length'].isin(['50km', '50mi'])]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745143,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,12:42:03 h,NaN,VEN,1978.0,M,M35,3.937,129256
1745144,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,12:59:48 h,NaN,VEN,1983.0,M,M23,3.847,634416
1745145,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:00:00 h,NaN,VEN,1968.0,M,M45,3.846,634417
1745146,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:05:36 h,NaN,VEN,1982.0,M,M23,3.819,248690
1745147,2017,02.-03.12.2017,Travesía de la Sierra Ultra-Trail Noctura (VEN),50km,47,13:05:36 h,NaN,VEN,1968.0,M,M45,3.819,252211

In [195]:
df[(df['Event distance/length'].isin(['50km','50mi'])) & (df['Year of event'] ==2018)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
661478,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29,17:05:58 h,NaN,USA,1972.0,M,M45,4.706,68122
661479,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29,18:13:01 h,NaN,USA,1953.0,M,M65,4.417,23336
661480,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29,18:49:58 h,NaN,USA,1986.0,M,M23,4.273,375022
661481,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29,23:30:00 h,NaN,USA,1952.0,M,M65,3.424,68273
661482,2018,27.-28.10.2018,Cactus Rose 50 Mile (USA),50mi,29,25:40:10 h,NaN,USA,1951.0,M,M65,3.135,341648

In [196]:
df[df['Event name'] == 'Yankee Springs 50 Mile Winter Challenge (USA)']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59
60,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:32:16 h,"*Olaton, KY",USA,1995.0,M,MU23,6.418,60
61,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:39:36 h,"*Wyoming, MI",USA,1979.0,M,M35,6.356,61
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63
717634,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,7:47:39 h,"*Kalamazoo, MI",USA,1982.0,M,M23,10.324,119568
717635,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,8:10:27 h,"*Midland, MI",USA,1979.0,M,M35,9.844,180388
717636,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,8:23:45 h,"*East Grand Rapids, MI",USA,1970.0,M,M45,9.584,57187
717637,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,8:59:38 h,"*Eaton Rapids, MI",USA,1969.0,M,M45,8.947,78245
717638,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,9:07:36 h,"*Chicago, IL",USA,1989.0,M,M23,8.817,104
717639,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:19:56 h,"*Rochester Hills, MI",USA,1975.0,M,M40,7.788,78294
717640,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:27:26 h,"*Grand Rapids, MI",USA,1980.0,M,M35,7.695,396222
717641,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:38:46 h,"*Durango, CO",USA,1991.0,M,M23,7.558,396223
717642,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:42:03 h,"*New Hudson, MI",USA,1983.0,F,W23,7.52,11992
717643,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:44:09 h,"*Grand Rapids, MI",USA,1977.0,F,W35,7.495,62
717644,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,10:57:54 h,"*Johnston, IA",USA,1977.0,F,W35,7.339,375039
717645,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,11:04:03 h,"*Royal Oak, MI",USA,1973.0,M,M40,7.271,244130
717646,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,11:18:02 h,"*Woodhaven, MI",USA,1961.0,F,W50,7.121,19252
717647,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,11:41:26 h,"*Ann Arbor, MI",USA,1981.0,F,W23,6.883,19279
717648,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,11:43:13 h,"*Grand Rapids, MI",USA,1965.0,M,M50,6.866,396224
717649,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:01:21 h,"*Bay City, MI",USA,1971.0,M,M40,6.693,78323
717650,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:20:17 h,"*South Rockwood, MI",USA,1959.0,M,M55,6.522,35698
717651,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:40:56 h,"*Fenton, MI",USA,1964.0,M,M50,6.345,396225
717652,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:51:17 h,"*Council Bluffs, IA",USA,1980.0,F,W35,6.26,375040
717653,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:51:19 h,"*Council Bluffs, IA",USA,1981.0,M,M23,6.259,396226
717654,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,12:56:14 h,"*Ypsilanti, MI",USA,1975.0,F,W40,6.22,322747
717655,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,13:29:29 h,"*Hamtramck, MI",USA,1958.0,M,M55,5.964,27051
717656,2016,02.01.2016,Yankee Springs 50 Mile Winter Challenge (USA),50mi,23,13:45:16 h,"*Lansing, MI",USA,1975.0,M,M40,5.85,282327
1231220,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,8:56:55 h,"*Holland, MI",USA,1978.0,M,M35,8.992,62355
1231221,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:01:24 h,"*Grand Rapids, MI",USA,1976.0,M,M40,8.918,178555
1231222,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:50:30 h,"*Midland, MI",USA,1979.0,M,M35,8.176,180388
1231223,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,10:16:50 h,"*Auburn, MI",USA,1985.0,M,M23,7.827,47019
1231224,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,10:33:49 h,"*Cadillac, MI",USA,1973.0,M,M40,7.617,221150
1231225,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,10:34:12 h,"*Fennville, MI",USA,1971.0,F,W45,7.613,32046
1231226,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,10:52:29 h,"*Grand Rapids, MI",USA,1977.0,F,W35,7.399,62
1231227,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:07:50 h,"*Guelph, ON",CAN,1982.0,M,M23,6.633,87090
1231228,2017,07.01.2017,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:35:43 h,"*Utica, MI",USA,1986.0,M,M23,6.389,58

In [197]:
df[df['Event name'] == 'Yankee Springs 50 Mile Winter Challenge (USA)']['Event name'].str.split('(')

55         [Yankee Springs 50 Mile Winter Challenge , USA)]
56         [Yankee Springs 50 Mile Winter Challenge , USA)]
57         [Yankee Springs 50 Mile Winter Challenge , USA)]
58         [Yankee Springs 50 Mile Winter Challenge , USA)]
59         [Yankee Springs 50 Mile Winter Challenge , USA)]
60         [Yankee Springs 50 Mile Winter Challenge , USA)]
61         [Yankee Springs 50 Mile Winter Challenge , USA)]
62         [Yankee Springs 50 Mile Winter Challenge , USA)]
63         [Yankee Springs 50 Mile Winter Challenge , USA)]
717634     [Yankee Springs 50 Mile Winter Challenge , USA)]
717635     [Yankee Springs 50 Mile Winter Challenge , USA)]
717636     [Yankee Springs 50 Mile Winter Challenge , USA)]
717637     [Yankee Springs 50 Mile Winter Challenge , USA)]
717638     [Yankee Springs 50 Mile Winter Challenge , USA)]
717639     [Yankee Springs 50 Mile Winter Challenge , USA)]
717640     [Yankee Springs 50 Mile Winter Challenge , USA)]
717641     [Yankee Springs 50 Mile Winter Challenge , USA)]
717642     [Yankee Springs 50 Mile Winter Challenge , USA)]
717643     [Yankee Springs 50 Mile Winter Challenge , USA)]
717644     [Yankee Springs 50 Mile Winter Challenge , USA)]
717645     [Yankee Springs 50 Mile Winter Challenge , USA)]
717646     [Yankee Springs 50 Mile Winter Challenge , USA)]
717647     [Yankee Springs 50 Mile Winter Challenge , USA)]
717648     [Yankee Springs 50 Mile Winter Challenge , USA)]
717649     [Yankee Springs 50 Mile Winter Challenge , USA)]
717650     [Yankee Springs 50 Mile Winter Challenge , USA)]
717651     [Yankee Springs 50 Mile Winter Challenge , USA)]
717652     [Yankee Springs 50 Mile Winter Challenge , USA)]
717653     [Yankee Springs 50 Mile Winter Challenge , USA)]
717654     [Yankee Springs 50 Mile Winter Challenge , USA)]
717655     [Yankee Springs 50 Mile Winter Challenge , USA)]
717656     [Yankee Springs 50 Mile Winter Challenge , USA)]
1231220    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231221    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231222    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231223    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231224    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231225    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231226    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231227    [Yankee Springs 50 Mile Winter Challenge , USA)]
1231228    [Yankee Springs 50 Mile Winter Challenge , USA)]
Name: Event name, dtype: object

In [198]:
df[df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1742391,2017,03.12.2017,Vista Verde Skyline Run (USA),50km,22,7:30:48 h,"*San Jose, CA",USA,1967.0,M,M45,6.655,68121
1742392,2017,03.12.2017,Vista Verde Skyline Run (USA),50km,22,8:00:18 h,"*Castro Valley, CA",USA,1967.0,M,M45,6.246,25955
1744873,2017,03.12.2017,Pullman Winter Ultra 50K (USA),50km,3,3:56:26 h,"*Pullman, WA",USA,1973.0,M,M40,12.689,101016
1744874,2017,03.12.2017,Pullman Winter Ultra 50K (USA),50km,3,4:35:36 h,"*Moscow, ID",USA,1978.0,M,M35,10.885,65422
1744875,2017,03.12.2017,Pullman Winter Ultra 50K (USA),50km,3,5:28:10 h,"*Lewiston, ID",USA,1961.0,M,M55,9.142,65423

In [199]:
df2 =df[(df['Event distance/length'].isin(['50km','50mi'])) & (df['Year of event'] ==2018) & (df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA')]

In [200]:
df2.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59
60,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:32:16 h,"*Olaton, KY",USA,1995.0,M,MU23,6.418,60
61,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:39:36 h,"*Wyoming, MI",USA,1979.0,M,M35,6.356,61
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge (USA),50mi,9,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63
64,2018,06.01.2018,Yankee Springs 50 km Winter Challenge (USA),50km,36,5:09:40 h,"*Okemos, MI",USA,1991.0,F,W23,9.688,64

In [201]:
df2.shape

(64299, 13)

In [202]:
#remove USA from event name

In [203]:
df2['Event name'].str.split('(').str.get(0)

55        Yankee Springs 50 Mile Winter Challenge
56        Yankee Springs 50 Mile Winter Challenge
57        Yankee Springs 50 Mile Winter Challenge
58        Yankee Springs 50 Mile Winter Challenge
59        Yankee Springs 50 Mile Winter Challenge
                            ...
661478                        Cactus Rose 50 Mile
661479                        Cactus Rose 50 Mile
661480                        Cactus Rose 50 Mile
661481                        Cactus Rose 50 Mile
661482                        Cactus Rose 50 Mile
Name: Event name, Length: 64299, dtype: object

In [204]:
df2['Event name'] = df2['Event name'].str.split('(').str.get(0)

/tmp/ipython-input-3473829760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Event name'] = df2['Event name'].str.split('(').str.get(0)

In [205]:
df2.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,9:53:05 h,"*Middleville, MI",USA,1983.0,M,M23,8.141,55
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:09:35 h,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:33:00 h,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:38:17 h,"*Utica, MI",USA,1986.0,M,M23,6.914,58
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:56:35 h,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59
60,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,12:32:16 h,"*Olaton, KY",USA,1995.0,M,MU23,6.418,60
61,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,12:39:36 h,"*Wyoming, MI",USA,1979.0,M,M35,6.356,61
62,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,12:39:36 h,"*Grand Rapids, MI",USA,1977.0,F,W40,6.356,62
63,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,13:24:05 h,"*Lansing, MI",USA,1990.0,F,W23,6.004,63
64,2018,06.01.2018,Yankee Springs 50 km Winter Challenge,50km,36,5:09:40 h,"*Okemos, MI",USA,1991.0,F,W23,9.688,64

In [206]:
#clean up the althete age

In [207]:
df2 ['Athlete_age'] = 2018 - df2['Athlete year of birth']

/tmp/ipython-input-3523140396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2 ['Athlete_age'] = 2018 - df2['Athlete year of birth']

In [208]:
#remove h from athlete performance

In [209]:
df2['Athlete performance'] = df2['Athlete performance'].str.split(' ').str.get(0)

/tmp/ipython-input-2477507555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Athlete performance'] = df2['Athlete performance'].str.split(' ').str.get(0)

In [210]:
df2.head(5)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID,Athlete_age
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,9:53:05,"*Middleville, MI",USA,1983.0,M,M23,8.141,55,35.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:09:35,"*Waterloo, ON",CAN,1977.0,F,W40,7.211,56,41.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:33:00,"*Kitchener, ON",CAN,1976.0,M,M40,6.967,57,42.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:38:17,"*Utica, MI",USA,1986.0,M,M23,6.914,58,32.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:56:35,"*Grass Lake, MI",USA,1988.0,M,M23,6.738,59,30.0

In [211]:
# drop columns: Athelte country, athlete age category, Athlete year of birth , Athlete  Club

In [212]:
df2 = df2.drop(['Athlete club', 'Athlete country' ,'Athlete year of birth' ,'Athlete age category'],axis=1)

In [213]:
df2.head(5)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,9:53:05,M,8.141,55,35.0
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:09:35,F,7.211,56,41.0
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:33:00,M,6.967,57,42.0
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:38:17,M,6.914,58,32.0
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:56:35,M,6.738,59,30.0

In [214]:
#clean up null values

In [215]:
df2.isna().sum()

Year of event                  0
Event dates                    0
Event name                     0
Event distance/length          0
Event number of finishers      0
Athlete performance            0
Athlete gender                 0
Athlete average speed          0
Athlete ID                     0
Athlete_age                  575
dtype: int64

In [216]:
df2[df2['Athlete_age'].isna()==1]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
453,2018,01.01.2018,Red Eye 50km,50km,21,5:10:00,M,9.677,453,NaN
456,2018,01.01.2018,Red Eye 50km,50km,21,5:44:00,M,8.721,456,NaN
459,2018,01.01.2018,Red Eye 50km,50km,21,6:07:00,M,8.174,459,NaN
460,2018,01.01.2018,Red Eye 50km,50km,21,6:12:00,M,8.065,460,NaN
13214,2018,17.03.2018,Lt. JC Stone 50K UltraMarathon,50km,34,4:54:43,F,10.179,12483,NaN
...,...,...,...,...,...,...,...,...,...,...
659684,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133,8:24:14,F,5.95,374269,NaN
659685,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133,8:25:12,F,5.938,358717,NaN
659688,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133,8:29:59,M,5.883,204804,NaN
659689,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133,8:31:30,F,5.865,374272,NaN
659690,2018,27.10.2018,Lake Hodges Trail Fest 50K,50km,133,8:35:28,M,5.82,374273,NaN

In [217]:
df2 = df2.dropna()

In [218]:
df2.shape

(63724, 10)

In [219]:
# check for duplicates

In [220]:
df2[df2.duplicated()==1]

Empty DataFrame
Columns: [Year of event, Event dates, Event name, Event distance/length, Event number of finishers, Athlete performance, Athlete gender, Athlete average speed, Athlete ID, Athlete_age]
Index: []

In [221]:
df2.reset_index(drop=True)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athlete_age
0,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,9:53:05,M,8.141,55,35.0
1,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:09:35,F,7.211,56,41.0
2,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:33:00,M,6.967,57,42.0
3,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:38:17,M,6.914,58,32.0
4,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:56:35,M,6.738,59,30.0
...,...,...,...,...,...,...,...,...,...,...
63719,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29,17:05:58,M,4.706,68122,46.0
63720,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29,18:13:01,M,4.417,23336,65.0
63721,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29,18:49:58,M,4.273,375022,32.0
63722,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29,23:30:00,M,3.424,68273,66.0
63723,2018,27.-28.10.2018,Cactus Rose 50 Mile,50mi,29,25:40:10,M,3.135,341648,67.0

In [222]:
#fix types

In [223]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete gender                object
Athlete average speed         object
Athlete ID                     int64
Athlete_age                  float64
dtype: object

In [224]:
df2['Athlete_age'] = df2['Athlete_age'].astype(int)

In [225]:
df2['Athlete average speed'] = df2['Athlete average speed'].astype(float)

In [226]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete gender                object
Athlete average speed        float64
Athlete ID                     int64
Athlete_age                    int64
dtype: object

In [227]:
#rename columns
#Year of event          Year_of_event
#Event dates	          Event_dates
#Event name	            Event_name
#Event distance/length	Event_distance/length
#Event number of finishers Event_number_of_finishers
#Athlete performance	  Athlete_performance
#Athlete gender	        Athlete_gender
#Athlete average speed	Athlete_average_speed
#Athlete ID	            Athlete_ID

In [228]:
df2.rename(columns ={
    'Year of event':'Year',
    'Event dates':'Race_date',
    'Event name':'Race_name',
    'Event distance/length':'Race_length',
    'Event number of finishers':'Race_number_of_finishers',
    'Athlete performance':'Athlete_performance',
    'Athlete gender':'Athlete_gender',
    'Athlete average speed':'Athlete_average_speed',
    'Athlete ID':'Athlete_ID'
    },inplace=True)

In [229]:
df2.head()

,Year,Race_date,Race_name,Race_length,Race_number_of_finishers,Athlete_performance,Athlete_gender,Athlete_average_speed,Athlete_ID,Athlete_age
55,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,9:53:05,M,8.141,55,35
56,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:09:35,F,7.211,56,41
57,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:33:00,M,6.967,57,42
58,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:38:17,M,6.914,58,32
59,2018,06.01.2018,Yankee Springs 50 Mile Winter Challenge,50mi,9,11:56:35,M,6.738,59,30

In [230]:
df3= df2[['Race_date','Race_name','Year','Race_length','Race_number_of_finishers','Athlete_ID','Athlete_gender','Athlete_performance','Athlete_average_speed','Athlete_age']]

In [231]:
df3.head(5)

,Race_date,Race_name,Year,Race_length,Race_number_of_finishers,Athlete_ID,Athlete_gender,Athlete_performance,Athlete_average_speed,Athlete_age
55,06.01.2018,Yankee Springs 50 Mile Winter Challenge,2018,50mi,9,55,M,9:53:05,8.141,35
56,06.01.2018,Yankee Springs 50 Mile Winter Challenge,2018,50mi,9,56,F,11:09:35,7.211,41
57,06.01.2018,Yankee Springs 50 Mile Winter Challenge,2018,50mi,9,57,M,11:33:00,6.967,42
58,06.01.2018,Yankee Springs 50 Mile Winter Challenge,2018,50mi,9,58,M,11:38:17,6.914,32
59,06.01.2018,Yankee Springs 50 Mile Winter Challenge,2018,50mi,9,59,M,11:56:35,6.738,30